apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-micro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-micro
  template:
    metadata:
      labels:
        app: go-micro
      annotations:
        timestamp: {{ now | quote }}
    spec:
      containers:
      - name: go-micro
        image: local/go-micro:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: postgres-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: gomicro
        - name: DB_USER
          value: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-postgresql
              key: postgresql-password

        ports:
        - containerPort: 8080
