apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-micro-ing
  # annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gomicro.kube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-micro-svc
            port:
              number: 80
