apiVersion: v1
kind: Service
metadata:
  name: go-micro-svc
  labels:
    app: gomicro-svc
    release: prometheus
spec:
  selector:
    app: go-micro
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
